# Generated by Django 5.2.6 on 2025-11-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credential',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='credential',
            name='name',
            field=models.CharField(default='Default Key', max_length=100),
        ),
    ]
