# Generated by Django 5.2.6 on 2025-11-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='agent',
            name='web_search_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='agent',
            name='provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI'), ('CLAUDE', 'Anthropic Claude'), ('GEMINI', 'Google Gemini')], max_length=20),
        ),
    ]
