# Generated by Django 5.2.6 on 2025-11-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='max_turns',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.CharField(default='General Discussion', max_length=255),
        ),
    ]
